### ISSUE TITLE
Using your work

### ISSUE THREAD

**Issue by jac459** [johnhamelink/snapcast-api-client#1]
Hello, I'd like to incorporate part of your work for one of my driver for Neeo (an IOT universal remote).
I will of course reference you but is there something else I should do ?
Thanks.

**Comment by johnhamelink** [comment]
I don't recommend you using this project, it's basically dead, it's tiny in scope, and it doesn't have a licence. You'd be better of building your own from scratch, or looking for another project. Thanks

**Comment by jac459** [comment]
I found another ressource, thanks.

**Comment by johnhamelink** [comment]
Glad to hear it! Best of luck with your project
